// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizManagmentSystem.DataContext;

#nullable disable

namespace QuizManagmentSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizManagmentSystem.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmPassword")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Depatment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("userEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfirmPassword = "rahul123",
                            Depatment = "Mechanical",
                            Email = "rahul@gmail.com",
                            FName = "Rahul",
                            Gender = "Male",
                            LName = "Adhao",
                            MName = "Sheshrao",
                            Password = "rahul123",
                            Phone = "7499458965"
                        },
                        new
                        {
                            Id = 2,
                            ConfirmPassword = "neha123",
                            Depatment = "CS",
                            Email = "neha@gmail.com",
                            FName = "Neha",
                            Gender = "Female",
                            LName = "Ahire",
                            MName = "Bhaskar",
                            Password = "neha123",
                            Phone = "9605000860"
                        },
                        new
                        {
                            Id = 3,
                            ConfirmPassword = "Mansi123",
                            Depatment = "CS",
                            Email = "Mansi@gmail.com",
                            FName = "Mansi",
                            Gender = "Female",
                            LName = "Goavkar",
                            MName = "Vithaldas",
                            Password = "Mansi123",
                            Phone = "9604086056"
                        },
                        new
                        {
                            Id = 4,
                            ConfirmPassword = "Niraj123",
                            Depatment = "Mechanical",
                            Email = "Nirnjan@gmail.com",
                            FName = "Nirnjan",
                            Gender = "Male",
                            LName = "Khatave",
                            MName = "Anil",
                            Password = "Niraj123",
                            Phone = "7499458965"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
